### ISSUE TITLE
Could not determine Java version when runnning step 3 in installation

### ISSUE THREAD

**Issue by nabergh** [tambetm/minecraft-py#3]
When running the code in step 3 of the installation, the following error is given before the process quits:

```
DEBUG:minecraft_py:b'\n'
DEBUG:minecraft_py:b'FAILURE: Build failed with an exception.\n'
DEBUG:minecraft_py:b'\n'
DEBUG:minecraft_py:b'* What went wrong:\n'
DEBUG:minecraft_py:b"Could not determine java version from '9-internal'.\n"
DEBUG:minecraft_py:b'\n'
DEBUG:minecraft_py:b'* Try:\n'
DEBUG:minecraft_py:b'Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.\n'
DEBUG:minecraft_py:b'\n'
DEBUG:minecraft_py:b'FAILURE: Build failed with an exception.\n'
DEBUG:minecraft_py:b'\n'
DEBUG:minecraft_py:b'* What went wrong:\n'
DEBUG:minecraft_py:b"Could not determine java version from '9-internal'.\n"
DEBUG:minecraft_py:b'\n'
DEBUG:minecraft_py:b'* Try:\n'
DEBUG:minecraft_py:b'Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.\n'
DEBUG:minecraft_py:b'\n'
DEBUG:minecraft_py:b'FAILURE: Build failed with an exception.\n'
DEBUG:minecraft_py:b'\n'
DEBUG:minecraft_py:b'* What went wrong:\n'
DEBUG:minecraft_py:b"Could not determine java version from '9-internal'.\n"
DEBUG:minecraft_py:b'\n'
DEBUG:minecraft_py:b'* Try:\n'
DEBUG:minecraft_py:b'Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.\n'
DEBUG:minecraft_py:b''
Traceback (most recent call last):
  File "mine_util.py", line 6, in <module>
    proc, port = minecraft_py.start()
  File "/home/nicholas/.local/lib/python3.5/site-packages/minecraft_py-0.0.2-py3.5.egg/minecraft_py/__init__.py", line 70, in start
    raise EOFError("Minecraft process finished unexpectedly")
EOFError: Minecraft process finished unexpectedly
```

My java version is:
```
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

I'm running this with python 3.5.2 on Ubuntu 16.04. The previous installation steps were completed without issue. Is there something I should have completed before step 1 of the installation in the readme?

**Comment by tambetm** [comment]
Hmm, it seems that Minecraft has trouble parsing OpenJDK Java version. To be honest, I used it with Oracle Java, so you could try installing that: https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04.

More information here: https://stackoverflow.com/questions/40924941/using-gradle-with-openjdk-1-9
